CREATE DATABASE PartnerGroup
GO

USE PartnerGroup

CREATE TABLE dbo.[Brand]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Brand] VARCHAR(300) NOT NULL,
	[DateRegister] DATETIME NOT NULL,
	[DateChange] DATETIME NULL,
	[Active] BIT NOT NULL
 )
 GO

CREATE TABLE dbo.[Patrimony]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[BrandId] BIGINT NOT NULL,
	[Patrimony] VARCHAR(800) NOT NULL,
	[Description] VARCHAR(800) NOT NULL,
	[NumberTumble] VARCHAR(15) NOT NULL,
	[DateRegister] DATETIME NOT NULL,
	[DateChange] DATETIME NULL,
	[Active] BIT NOT NULL

	FOREIGN KEY (BrandId) REFERENCES dbo.[Brand](id),
 )
 GO

